import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@/styles/layout.css";
//import "@/styles/normalize.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import Script from 'next/script';
import { SessionProvider } from '@/context/SessionContext';
import { EdgeStoreProvider } from "@/libs/edgestore";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Sneakicks",
  description: "Generated by create next app",
  // Puedes añadir otras metainformaciones aquí
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <meta charSet="UTF-8" />
        <meta httpEquiv="X-UA-Compatible" content="IE=edge" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        {/* <link rel="stylesheet" href="/css/index.css" /> */}
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="anonymous" />
        <link
          href="https://fonts.googleapis.com/css2?family=Montserrat:wght@400;700&family=Roboto&display=swap"
          rel="stylesheet"
        />
        <Script src="https://kit.fontawesome.com/f7b22d2da3.js" crossOrigin="anonymous" />
      </head>
      <body className={inter.className} id="layout">
        <SessionProvider>
          <EdgeStoreProvider>
            <Header />
            <main>{children}</main>
            <Footer />
          </EdgeStoreProvider>
        </SessionProvider>
      </body>
    </html>
  );
}
